from django.db import models
from django.conf import settings 
from django.utils.text import slugify
from django.utils import timezone


class Platform(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.name
    
    
class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name
    

class Game(models.Model):
    title = models.CharField(max_length=255)
    platforms = models.ManyToManyField(Platform, related_name="games")
    genre = models.ManyToManyField(Genre, related_name="games")
    description = models.TextField()
    release_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    cover_image = models.ImageField(upload_to="game_covers/", blank=True, null=True)
    content_type = models.CharField(max_length=20, null=True) # for querying (Game, Review, Guide)
    slug = models.SlugField(unique=True, default=None) # will be generated from title and author id to ensure uniqueness
    # Members/followers, "through" specifies the intermediate model to use, instead of m2m autogenerated hidden table
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, through="GameFollowers", related_name="joined_games")

     # Voting system
    upvotes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="game_upvotes", blank=True)
    downvotes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="game_downvotes", blank=True)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,  # references your custom User model
        null=True,
        on_delete=models.CASCADE,
        related_name="game_author"
    )


    def save(self, *args, **kwargs):
        # import traceback
        # print("Saving Game:", self.title, "slug:", self.slug)
        # traceback.print_stack(limit=5)  # shows where save() is called
        if not self.slug: # Only generate if slug is not already set
            base_slug = slugify(f"{self.author.id}-{self.title}")
            slug = base_slug
            counter = 1
            while Game.objects.filter(slug=slug).exists(): # ensure uniqueness
                slug = f"{base_slug}-{counter}" # add counter if slug exists
                counter += 1
            self.slug = slug
        super().save(*args, **kwargs)


    @property # with @property decorator, can call as game.approval_percentage like a normal field
    def approval_percentage(self):
        total_votes = self.upvotes.count() + self.downvotes.count()
        if total_votes == 0:
            return 0
        return round((self.upvotes.count() / total_votes) * 100, 1)
    

    @property
    def rating_color(self):
        """Returns color class depending on approval percentage."""
        rating = self.approval_percentage
        if rating >= 80:
            return "green"
        elif rating >= 50:
            return "orange"
        else:
            return "red"


    def __str__(self):
        return self.title
    

class GameFollowers(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    joined_at = models.DateTimeField(auto_now_add=True)
    is_moderator = models.BooleanField(default=False)

    class Meta:
        unique_together = ("user", "game")  # prevent duplicate joins


class Rating(models.Model):
    game = models.ForeignKey(Game, related_name="ratings", on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    value = models.PositiveIntegerField()  # e.g. 1–5 stars
    created_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("game", "author")  # prevent same user rating the same game multiple times

    def __str__(self):
            return f"{self.user} rated {self.game} {self.value}"