# Generated by Django 5.1.7 on 2025-09-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfollow_customuser_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
