# Generated by Django 5.1.7 on 2025-10-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_karma'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
