"""
Django settings for The_sidequest_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import environ
import os

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(os.path.dirname(os.path.dirname(__file__)), ".env"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY") # gets the value from .env file

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # set to False for production

# ALLOWED_HOSTS = []

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    env("RENDER_EXTERNAL_HOSTNAME"),
]

CSRF_TRUSTED_ORIGINS = [
    f"https://{env('RENDER_EXTERNAL_HOSTNAME')}",
]


# Application definition

INSTALLED_APPS = [
    'accounts',
    'content',
    'guides',
    'reviews',
    'channels',
    'widget_tweaks',
    'taggit',
    'cloudinary_storage', # for cloudinary media storage, remove this if collecting static files locally
    'cloudinary', # comment these two out for local development
    'django_filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # for serving static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'The_sidequest_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'The_sidequest_project.wsgi.application'

# ASGI
ASGI_APPLICATION = "The_sidequest_project.asgi.application"

# Dev channel layer in-memory (works for single process only)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# For production (recommended): use Redis
# CHANNEL_LAYERS = {
#   "default": {
#     "BACKEND": "channels_redis.core.RedisChannelLayer",
#     "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
#   }
# }

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# for local development using sqlite3
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# for production using DATABASE_URL from .env
DATABASES = {
    "default": env.db("DATABASE_URL", default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}")
}

# Force SSL for Supabase
if DATABASES["default"]["ENGINE"] == "django.db.backends.postgresql":
    DATABASES["default"]["OPTIONS"] = {"sslmode": "require"}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


# -----------------------------
# STATIC FILES
# -----------------------------
STATIC_URL = '/static/'

# Global project-level static folder
STATICFILES_DIRS = [BASE_DIR / "static"]

# Where collectstatic will collect files for production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise: serve static files with compression and cache-busting
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# -----------------------------
# MEDIA FILES
# -----------------------------
if DEBUG:
    # Local uploads for development
    MEDIA_URL = '/uploads/'
    MEDIA_ROOT = BASE_DIR / "uploads"
else:
    # Cloudinary storage for production uploads
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"
    MEDIA_URL = "/media/"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUD_NAME'),
    'API_KEY': env('API_KEY'),
    'API_SECRET': env('API_SECRET'),
    'SECURE': True,
}

# OAuth settings for IGDB API
CLIENT_ID = env("CLIENT_ID") # gets the value from .env file
CLIENT_SECRET = env("CLIENT_SECRET")
AUTHORIZATION = env("AUTHORIZATION")



