# Generated by Django 5.1.7 on 2025-08-25 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='discussion_post',
            new_name='discussion',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='guide_post',
            new_name='guide',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='review_post',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='content_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='guide',
            old_name='guide_type',
            new_name='type',
        ),
    ]
