# Generated by Django 5.1.7 on 2025-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_genre_platform_alter_game_author_remove_game_genre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='body',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
