# Generated by Django 5.1.7 on 2025-08-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_community_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='game',
        ),
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=None, unique=True),
        ),
    ]
