# Generated by Django 5.1.7 on 2025-08-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_topic_spoiler_alter_comments_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='community_banners/'),
        ),
        migrations.AddField(
            model_name='community',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='community_icons/'),
        ),
        migrations.AddField(
            model_name='game',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='game_covers/'),
        ),
    ]
