# Generated by Django 5.1.7 on 2025-09-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_comments_discussion_comments_topic_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='review',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='type',
        ),
        migrations.AddField(
            model_name='comments',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comments',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
