# Generated by Django 5.1.7 on 2025-09-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_comments_guide_remove_comments_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_icon',
            field=models.ImageField(blank=True, null=True, upload_to='game_icons/'),
        ),
    ]
