# Generated by Django 5.1.7 on 2025-09-09 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_game_game_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
    ]
