# Generated by Django 5.1.7 on 2025-09-10 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_comments_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
    ]
