# Generated by Django 5.1.7 on 2025-09-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_icon',
        ),
    ]
