# Generated by Django 5.1.7 on 2025-09-17 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_gamefollowers_game_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
