# Generated by Django 5.1.7 on 2025-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_community_moderators'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='rules',
            field=models.TextField(null=True),
        ),
    ]
