# Generated by Django 5.1.7 on 2025-09-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_topic_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='rules',
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(null=True),
        ),
    ]
