# Generated by Django 5.1.7 on 2025-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0023_remove_topic_rules_community_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='game',
        ),
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
