# Generated by Django 5.1.7 on 2025-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_remove_review_author_remove_review_game_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='topic',
            name='content_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
