# Generated by Django 5.1.7 on 2025-10-17 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_rename_content_topic_text_topic_content_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='game_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='game_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
