# Generated by Django 5.1.7 on 2025-10-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_game_downvotes_game_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='average_rating',
        ),
    ]
