# Generated by Django 5.2.7 on 2025-10-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('comment', 'Comment'), ('reply', 'Reply'), ('message', 'Message'), ('topic', 'Topic')], max_length=50),
        ),
    ]
