# Generated by Django 5.2.7 on 2025-10-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_notification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
