# Generated by Django 5.2.7 on 2025-10-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_notification_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('upvote_topic', 'Upvote_topic'), ('upvote_comment', 'Upvote_comment'), ('comment', 'Comment'), ('reply', 'Reply'), ('message', 'Message'), ('topic', 'Topic')], max_length=50),
        ),
    ]
