# Generated by Django 5.2.7 on 2025-11-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_alter_notification_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
